[project]
name = "email-check-app"
version = "0.1.0"
description = "AI Email Application Tracker"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "google-api-python-client",
    "google-auth-oauthlib",
    "google-generativeai",
    "langsmith",
    "pandas",
    "pydantic",
    "python-dotenv",
    "reportlab",
    "sqlalchemy",
    "streamlit",
]